fx_version 'cerulean'
game 'rdr3'
rdr3_warning 'I acknowledge that this is a prerelease build of RedM, and I am aware my resources *will* become incompatible once RedM ships.'
lua54 'yes'
description 'Development-only Organizations export-boundary acceptance fixture'
version '0.1.0'
server_script 'server.lua'
dependency 'feather-organizations'
